[package]
name = "aap-rust-sandbox"
version = "0.1.0"
edition = "2018"

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }

[dev-dependencies]
anyhow = "1.0.39"
rand = "0.8.4"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.5", features = ["macros", "rt-multi-thread"] }
